//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jatékosok
    {
        public byte Mezszám { get; set; }
        public string Név { get; set; }
        public string Pozició { get; set; }
        public Nullable<decimal> Gól { get; set; }
        public Nullable<decimal> Gólpassz { get; set; }
    }
}
